import "bootstrap/dist/css/bootstrap.min.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, info, team }) {
  return (
    <div>
      <div>{children}</div>

      <hr />

      <div className="d-flex justify-content-between w-100 px-4">
        <div className="border p-3">{info}</div>
        <div className="border p-3">{team}</div>
      </div>
    </div>
  );
}
